Switch to Bash rmate.

diff --git a/thirdparty/rmate b/thirdparty/rmate
--- a/thirdparty/rmate
+++ b/thirdparty/rmate
@@ -1,191 +1,386 @@
-#!/usr/bin/env ruby
-# encoding: UTF-8
+#!/usr/bin/env bash
 
-$VERBOSE = true                         # -w
-$KCODE   = "U" if RUBY_VERSION < "1.9"  # -KU
+# rmate
+# Copyright (C) 2011-2016 by Harald Lapp <harald@octris.org>
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-require 'optparse'
-require 'socket'
-require 'tempfile'
-require 'yaml'
-require 'fileutils'
-require 'rmate'
+#
+# This script can be found at:
+# https://github.com/aurora/rmate
+#
 
-VERSION_STRING = "rmate version #{Rmate::VERSION} (#{Rmate::DATE})"
+#
+# This script is a pure bash compatible shell script implementing remote
+# textmate functionality
+#
 
-class Settings
-  attr_accessor :host, :port, :wait, :force, :verbose, :lines, :names, :types
+#
+# Thanks very much to all users and contributors! All bug-reports,
+# feature-requests, patches, etc. are greatly appreciated! :-)
+#
 
-  def initialize
-    @host, @port = 'localhost', 52698
+# init
+#
+version="0.9.8"
+version_date="2016-04-14"
+version_string="rmate-sh $version ($version_date)"
 
-    @wait    = false
-    @force   = false
-    @verbose = false
-    @lines   = []
-    @names   = []
-    @types   = []
+# determine hostname
+function hostname_command(){
+    if command -v hostname >/dev/null 2>&1; then
+        echo "hostname"
+    else {
+        HOSTNAME_DESCRIPTOR="/proc/sys/kernel/hostname"
+        if test -r "$HOSTNAME_DESCRIPTOR"; then
+            echo "cat $HOSTNAME_DESCRIPTOR"
+        else
+            echo "hostname"
+        fi
+        }
+    fi
+}
 
-    read_disk_settings
+hostname=$($(hostname_command))
 
-    @host = ENV['RMATE_HOST'].to_s if ENV.has_key? 'RMATE_HOST'
-    @port = ENV['RMATE_PORT'].to_i if ENV.has_key? 'RMATE_PORT'
+# default configuration
+host=localhost
+port=52698
+eval home=$(builtin printf "~%q" "${SUDO_USER:-$LOGNAME}")
 
-    parse_cli_options
+function load_config {
+    local rc_file=$1
+    local row
 
-    @host = parse_ssh_connection if @host == 'auto'
-  end
+    local host_pattern="^host(:[[:space:]]+|=)([^ ]+)"
+    local port_pattern="^port(:[[:space:]]+|=)([0-9]+)"
 
-  def read_disk_settings
-    [ "/etc/rmate.rc", "~/.rmate.rc"].each do |current_file|
-      file = File.expand_path current_file
-      if File.exist? file
-        params = YAML::load(File.open(file))
-        @host = params["host"] unless params["host"].nil?
-        @port = params["port"] unless params["port"].nil?
-      end
-    end
-  end
+    if [ -f "$rc_file" ]; then
+        while read row; do
+            if [[ "$row" =~ $host_pattern ]]; then
+                host=${BASH_REMATCH[2]}
+            elif [[ "$row" =~ $port_pattern ]]; then
+                port=${BASH_REMATCH[2]}
+            fi
+        done < "$rc_file"
+    fi
+}
 
-  def parse_cli_options
-    OptionParser.new do |o|
-      o.on(           '--host=name',       "Connect to host.", "Use 'auto' to detect the host from SSH.", "Defaults to #{@host}.") { |v| @host    = v          }
-      o.on('-p',      '--port=#', Integer, "Port number to use for connection.", "Defaults to #{@port}.")                          { |v| @port    = v          }
-      o.on('-w',      '--[no-]wait',       'Wait for file to be closed by TextMate.')                                              { |v| @wait    = v          }
-      o.on('-l',      '--line [NUMBER]',   'Place caret on line [NUMBER] after loading file.')                                     { |v| @lines <<= v          }
-      o.on('-m',      '--name [NAME]',     'The display name shown in TextMate.')                                                  { |v| @names <<= v          }
-      o.on('-t',      '--type [TYPE]',     'Treat file as having [TYPE].')                                                         { |v| @types <<= v          }
-      o.on('-f',      '--force',           'Open even if the file is not writable.')                                               { |v| @force   = v          }
-      o.on('-v',      '--verbose',         'Verbose logging messages.')                                                            { |v| @verbose = v          }
-      o.on_tail('-h', '--help',            'Show this message.')                                                                   { puts o; exit              }
-      o.on_tail(      '--version',         'Show version.')                                                                        { puts VERSION_STRING; exit }
-      o.parse!
-    end
-  end
+for i in "/etc/${0##*/}" $home/."${0##*/}/${0##*/}.rc" $home/."${0##*/}.rc"; do
+    load_config $i
+done
 
-  def parse_ssh_connection
-    ENV['SSH_CONNECTION'].nil? ? 'localhost' : ENV['SSH_CONNECTION'].split(' ').first
-  end
-end
+host="${RMATE_HOST:-$host}"
+port="${RMATE_PORT:-$port}"
 
-class Command
-   def initialize(name)
-     @command   = name
-     @variables = {}
-     @data      = nil
-     @size      = nil
-   end
 
-   def []=(name, value)
-     @variables[name] = value
-   end
+# misc initialization
+filepath=""
+selection=""
+displayname=""
+filetype=""
+verbose=false
+nowait=true
+force=false
 
-   def read_file(path)
-     @size = File.size(path)
-     @data = File.open(path, "rb") { |io| io.read(@size) }
-   end
+# process command-line parameters
+#
+function showusage {
+    echo "usage: $(basename $0) [arguments] file-path  edit specified file
+   or: $(basename $0) [arguments] -          read text from stdin
 
-   def send(socket)
-     socket.puts @command
-     @variables.each_pair do |name, value|
-       value = 'yes' if value === true
-       socket.puts "#{name}: #{value}"
-     end
-     if @data
-       socket.puts "data: #{@size}"
-       socket.puts @data
-     end
-     socket.puts
-   end
-end
+-H, --host HOST  Connect to HOST. Use 'auto' to detect the host from
+                 SSH. Defaults to $host.
+-p, --port PORT  Port number to use for connection. Defaults to $port.
+-w, --[no-]wait  Wait for file to be closed by TextMate.
+-l, --line LINE  Place caret on line number after loading file.
++N               Alias for --line, if N is a number (eg.: +5).
+-m, --name NAME  The display name shown in TextMate.
+-t, --type TYPE  Treat file as having specified type.
+-n, --new        Open in a new window (Sublime Text).
+-f, --force      Open even if file is not writable.
+-v, --verbose    Verbose logging messages.
+-h, --help       Display this usage information.
+    --version    Show version and exit.
+"
+}
 
-def handle_save(socket, variables, data)
-  path = variables["token"]
-  if File.writable?(path) || !File.exists?(path)
-    $stderr.puts "Saving #{path}" if $settings.verbose
-    begin
-      backup_path = "#{path}~"
-      backup_path = "#{backup_path}~" while File.exists? backup_path
-      FileUtils.cp(path, backup_path, :preserve => true) if File.exists?(path)
-      open(path, 'wb') { |file| file << data }
-      File.unlink(backup_path) if File.exist? backup_path
-    rescue
-      # TODO We probably want some way to notify the server app that the save failed
-      $stderr.puts "Save failed! #{$!}" if $settings.verbose
-    end
-  else
-    $stderr.puts "Skipping save, file not writable." if $settings.verbose
-  end
-end
+function log {
+    if [[ $verbose = true ]]; then
+        echo "$@" 1>&2
+    fi
+}
 
-def handle_close(socket, variables, data)
-  path = variables["token"]
-  $stderr.puts "Closed #{path}" if $settings.verbose
-end
+function dirpath {
+    (cd `dirname $1` >/dev/null 2>/dev/null; pwd -P)
+}
 
-def handle_cmd(socket)
-  cmd = socket.readline.chomp
+function canonicalize {
+    filepath="$1"
+    dir=`dirpath "$filepath"`
+    if [ -L "$filepath" ]; then
+        relativepath=`cd "$dir"; readlink \`basename "$filepath"\``
+        result=`dirpath "$relativepath"`/`basename "$relativepath"`
+    else
+        result=`basename "$filepath"`
+        if [ "$dir" = '/' ]; then
+            result="$dir$result"
+        else
+            result="$dir/$result"
+        fi
+    fi
+    echo $result
+}
 
-  variables = {}
-  data = ""
+while [[ "${1:0:1}" = "-" || "$1" =~ ^\+([0-9]+)$ ]]; do
+    case $1 in
+        -)
+            break
+            ;;
+        -H|--host)
+            host=$2
+            shift
+            ;;
+        -p|--port)
+            port=$2
+            shift
+            ;;
+        -w|--wait)
+            nowait=false
+            ;;
+        --no-wait)
+            nowait=true
+            ;;
+        -l|--line)
+            selection=$2
+            shift
+            ;;
+        -m|--name)
+            displayname=$2
+            shift
+            ;;
+        -t|--type)
+            filetype=$2
+            shift
+            ;;
+        -n|--new)
+            new=true
+            ;;
+        -f|--force)
+            force=true
+            ;;
+        -v|--verbose)
+            verbose=true
+            ;;
+        --version)
+            echo $version_string
+            exit 1
+            ;;
+        -h|-\?|--help)
+            showusage
+            exit 1
+            ;;
+        +[0-9]*)
+            selection=${1:1}
+            ;;
+        *)
+            showusage
+            exit 1
+            ;;
+    esac
 
-  while line = socket.readline.chomp
-    break if line.empty?
-    name, value     = line.split(': ', 2)
-    variables[name] = value
-    data << socket.read(value.to_i) if name == "data"
-  end
-  variables.delete("data")
+    shift
+done
 
-  case cmd
-  when "save"   then handle_save(socket, variables, data)
-  when "close"  then handle_close(socket, variables, data)
-  else          abort "Received unknown command “#{cmd}”, exiting."
-  end
-end
+if [[ "$host" = "auto" && "$SSH_CONNECTION" != "" ]]; then
+    host=${SSH_CONNECTION%% *}
+fi
 
-def connect_and_handle_cmds(host, port, cmds)
-  socket = TCPSocket.new(host, port)
-  server_info = socket.readline.chomp
-  $stderr.puts "Connect: ‘#{server_info}’" if $settings.verbose
+filepath="$1"
 
-  cmds.each { |cmd| cmd.send(socket) }
+if [ "$filepath" = "" ]; then
+    if [[ $nowait = false ]]; then
+        filepath='-'
+    else
+        case "$-" in
+            *i*)
+                showusage
+                exit 1
+                ;;
+            *)
+                filepath='-'
+                ;;
+        esac
+    fi
+fi
 
-  socket.puts "."
-  handle_cmd(socket) while !socket.eof?
-  socket.close
-  $stderr.puts "Done" if $settings.verbose
-end
+shift
+if [ ! "${#@}" -eq 0 ]; then
+    echo "There is more than one file specified. Opening only $filepath and ignoring other."
+fi
 
-## MAIN
+if [ "$filepath" != "-" ]; then
+    realpath=`canonicalize "$filepath"`
+    log $realpath
 
-$settings = Settings.new
+    if [ -d "$filepath" ]; then
+        echo "$filepath is a directory and rmate is unable to handle directories."
+        exit 1
+    fi
 
-## Parse arguments.
-cmds = []
-ARGV.each_index do |idx|
-  path = ARGV[idx]
-  abort "File #{path} is not writable! Use -f/--force to open anyway." unless $settings.force or File.writable? path or not File.exists? path
-  $stderr.puts "File #{path} is not writable. Opening anyway." if not File.writable? path and File.exists? path and $settings.verbose
-  cmd                 = Command.new("open")
-  cmd['display-name'] = "#{Socket.gethostname}:#{path}"
-  cmd['display-name'] = $settings.names[idx] if $settings.names.length > idx
-  cmd['real-path']    = File.expand_path(path)
-  cmd['data-on-save'] = true
-  cmd['re-activate']  = true
-  cmd['token']        = path
-  cmd['selection']    = $settings.lines[idx] if $settings.lines.length > idx
-  cmd['file-type']    = $settings.types[idx] if $settings.types.length > idx
-  cmd.read_file(path)               if File.exist? path
-  cmd['data']         = "0"     unless File.exist? path
-  cmds << cmd
-end
+    if [ -f "$realpath" ] && [ ! -w "$realpath" ]; then
+        if [[ $force = false ]]; then
+            echo "File $filepath is not writable! Use -f to open anyway."
+            exit 1
+        elif [[ $verbose = true ]]; then
+            log "File $filepath is not writable! Opening anyway."
+        fi
+    fi
 
-unless $settings.wait
-  pid = fork do
-    connect_and_handle_cmds($settings.host, $settings.port, cmds)
-  end
-  Process.detach(pid)
+    if [ "$displayname" = "" ]; then
+        displayname="$hostname:$filepath"
+    fi
 else
-  connect_and_handle_cmds($settings.host, $settings.port, cmds)
-end
+    displayname="$hostname:untitled"
+fi
+
+#------------------------------------------------------------
+# main
+#------------------------------------------------------------
+function handle_connection {
+    local cmd
+    local name
+    local value
+    local token
+    local tmp
+
+    while read 0<&3; do
+        REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
+        REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
+
+        cmd=$REPLY
+
+        token=""
+        tmp=""
+
+        while read 0<&3; do
+            REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"
+            REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"
+
+            if [ "$REPLY" = "" ]; then
+                break
+            fi
+
+            name="${REPLY%%:*}"
+            value="${REPLY##*:}"
+            value="${value#"${value%%[![:space:]]*}"}"      # fix textmate syntax highlighting: "
+
+            case $name in
+                "token")
+                    token=$value
+                    ;;
+                "data")
+                    if [ "$tmp" = "" ]; then
+                        tmp="/tmp/rmate.$RANDOM.$$"
+                        touch "$tmp"
+                    fi
+
+                    dd bs=1 count=$value <&3 >>"$tmp" 2>/dev/null
+                    ;;
+                *)
+                    ;;
+            esac
+        done
+
+        if [[ "$cmd" = "close" ]]; then
+            log "Closing $token"
+            if [[ "$token" == "-" ]]; then
+                echo -n "$CONTENT"
+            fi
+        elif [[ "$cmd" = "save" ]]; then
+            log "Saving $token"
+            if [ "$token" != "-" ]; then
+                cat "$tmp" > "$token"
+            else
+                CONTENT=`cat "$tmp"`
+            fi
+            rm "$tmp"
+        fi
+    done
+
+    log "Done"
+}
+
+# connect to textmate and send command
+#
+exec 3<> /dev/tcp/$host/$port
+
+if [ $? -gt 0 ]; then
+    echo "Unable to connect to TextMate on $host:$port"
+    exit 1
+fi
+
+read server_info 0<&3
+
+log $server_info
+
+echo "open" 1>&3
+echo "display-name: $displayname" 1>&3
+echo "real-path: $realpath" 1>&3
+echo "data-on-save: yes" 1>&3
+echo "re-activate: yes" 1>&3
+echo "token: $filepath" 1>&3
+
+if [[ $new = true ]]; then
+    echo "new: yes"  1>&3
+fi
+
+if [ "$selection" != "" ]; then
+    echo "selection: $selection" 1>&3
+fi
+
+if [ "$filetype" != "" ]; then
+    echo "file-type: $filetype" 1>&3
+fi
+
+if [ "$filepath" != "-" ] && [ -f "$filepath" ]; then
+    filesize=`ls -lLn "$realpath" | awk '{print $5}'`
+    echo "data: $filesize" 1>&3
+    cat "$realpath" 1>&3
+elif [ "$filepath" = "-" ]; then
+    if [ -t 0 ]; then
+        echo "Reading from stdin, press ^D to stop"
+    else
+        log "Reading from stdin"
+    fi
+
+    # preserve trailing newlines
+    data=`cat; echo x`
+    data=${data%x}
+    filesize=$(echo -ne "$data" | wc -c)
+    echo "data: $filesize" 1>&3
+    echo -n "$data" 1>&3
+else
+    echo "data: 0" 1>&3
+fi
+
+echo 1>&3
+echo "." 1>&3
+
+if [[ $nowait = true ]]; then
+    exec </dev/null >/dev/null 2>/dev/null
+    ( (handle_connection &) &)
+else
+    handle_connection
+fi
